#! /usr/bin/env bash

# Starts Goliath server

if [ -a goliath.pid ]; then
  echo "Goliath.pid already present. Is server running?"
  exit 1
else
  bundle exec ruby main.rb -d -e prod -S goliath.sock
fi
