#! /usr/bin/env bash

# Starts Goliath server

if [ -a goliath.sock ]; then
  echo "Looks like the giant is already up."
  exit 1
else
  bundle exec ruby main.rb -d -e prod -S goliath.sock
  echo "Fe fi fo fum!"
fi
